services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: wedding-gallery-backend-prod
    restart: always
    env_file:
      - ./apps/backend/.env.production
    ports:
      - "8000:8000"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: wedding-gallery-frontend-prod
    restart: always
    env_file:
      - ./apps/frontend/.env.production
    ports:
      - "80:3000"
    depends_on:
      - backend

