services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: wedding-gallery-backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    env_file:
      - apps/backend/.env
    depends_on:
      - postgres
      - minio
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_superuser &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - wedding-gallery-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: wedding-gallery-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    depends_on:
      - backend
    networks:
      - wedding-gallery-network

  postgres:
    image: postgres:15-alpine
    container_name: wedding-gallery-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - wedding-gallery-network

  minio:
    image: minio/minio:latest
    container_name: wedding-gallery-minio
    command: server /data --console-address ":9090"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    networks:
      - wedding-gallery-network

  mc:
    image: minio/mc
    container_name: wedding-gallery-mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
        echo 'Waiting for MinIO...';
        until mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        do
          sleep 1;
        done

        echo 'Creating bucket (if not exists)...';
        mc mb --ignore-existing minio/${MINIO_BUCKET_NAME}

        echo 'Setting bucket public...';
        mc anonymous set public minio/${MINIO_BUCKET_NAME}

        echo 'Done.';
        exit 0
      "
    networks:
      - wedding-gallery-network

volumes:
  postgres_data:
  minio_data:

networks:
  wedding-gallery-network:
    driver: bridge
